apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
        - image: basket-api # must much from ./kustomization.yaml -> images[0].name
          imagePullPolicy: IfNotPresent
          name: basket-api
          ports:
            - containerPort: 5200
          envFrom:
            - configMapKeyRef:
              name: basket-api
          resources:
            requests:
              memory: "32Mi"
              cpu: "60m"
            limits:
              memory: "128Mi"
              cpu: "100m"
